language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt clean buffered-config-test:test invalid-config-test:test coverage test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls
